#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-htmlunit
Version  : 2.18
Release  : 1
URL      : https://github.com/HtmlUnit/htmlunit/archive/HtmlUnit-2.18.tar.gz
Source0  : https://github.com/HtmlUnit/htmlunit/archive/HtmlUnit-2.18.tar.gz
Source1  : https://repo1.maven.org/maven2/net/sourceforge/htmlunit/htmlunit/2.18/htmlunit-2.18.jar
Source2  : https://repo1.maven.org/maven2/net/sourceforge/htmlunit/htmlunit/2.18/htmlunit-2.18.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : AFL-2.1 Apache-2.0 BSD-3-Clause BSD-3-Clause-Clear ICU LGPL-2.1 MIT
Requires: mvn-htmlunit-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-htmlunit package.
Group: Data

%description data
data components for the mvn-htmlunit package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.18
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.18

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.18
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.18


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.18/htmlunit-2.18.jar
/usr/share/java/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.18/htmlunit-2.18.pom
